name: Build LaTeX document
on: [create]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: dev 
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
          compiler: pdflatex
