name: Build LaTeX document
on:
  push:
    tags:
    - 'v*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: presentation.tex
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: notes.tex
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{github.event.commits[0].message}}
      - name: Upload Release Asset - Presentation
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./presentation.pdf
          asset_name: presentation-${{ github.ref }}.pdf
          asset_content_type: application/pdf
      - name: Upload Release Asset - Notes
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./notes.pdf
          asset_name: notes-${{ github.ref }}.pdf
          asset_content_type: application/pdf
